import Head from "next/head";
import { BsMoonStarsFill } from "react-icons/bs";
import { AiFillLinkedin, AiFillGithub, AiFillMail } from "react-icons/ai";
import Image from "next/image";
import Avatar from "../public/avatar.png";
import Hashtag from "../public/code.png";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Luchas Schmidt</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-roboto dark:text-white">
              Luchas Schmidt
            </h1>
            <ul className="flex items-center">
              <li>
                <BsMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl animate-bounce dark:text-white"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  ???
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">
              Hello, I'm Luchas Schmidt
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-white">
              I'm a B.Sc. Student and a Webdeveloper. Based in
              <span className="text-5xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-gray-100 to-red-600">
                {" "}
                Copenhagen
              </span>
            </h3>
            <p className="py-5 text-gray-800 leading-8 md:text-xl dark:text-white">
              Computer Science and Informatics student at
              <span className="text-teal-500"> Roskilde Universitet</span>.
            </p>
            <p className="py-1 text-gray-800 leading-8 md:text-xl dark:text-white">
              Junior Development Specialist at
              <span className="text-teal-500"> DaxMedia</span>.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 dark:text-white">
            <a
              className="transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 duration-300"
              href="https://www.linkedin.com/in/luchas-schmidt/"
            >
              <AiFillLinkedin />
            </a>
            <a
              className="transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 duration-300"
              href="https://github.com/Luchassmed"
            >
              <AiFillGithub />
            </a>
            <a
              className="transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 duration-300"
              href="mailto: kapot@live.dk"
            >
              <AiFillMail />
            </a>
          </div>
          <div className="relative mx-auto rounded-full w-80 h-80 mt-20 md:h-96 md:w-96">
            <Image src={Avatar} layout="fill" objectFit="cover" />
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white">Portfolio</h3>
            <p className="text-md py-2 leading-8 text-gray-600 dark:text-white">
              Most of the projects I have done have been in connection with
              exams and assignments during my schooling at{" "}
              <span className="text-teal-500">Roskilde Universitet</span>. The
              portfolio will be updated continuously...
            </p>
          </div>

          <div className="text-3xl flex justify-center gap-16 py-3 dark:text-white">
            <a
              href="https://github.com/Luchassmed"
              target="_blank"
              className="text-center shadow-lg p-10 rounded-xl my-10 transition ease-in-out delay-50 hover:-translate-y-1 hover:scale-110"
            >
              <Image src={Hashtag} width={100} height={100} />
              <h3 className="texl-lg font-medium pt-2 pb-8">
                ReactJS webapplication
              </h3>
              <p>Det her</p>
            </a>
            <a
              href="https://github.com/Luchassmed/react-api"
              target="_blank"
              className="text-center shadow-lg p-10 rounded-xl my-10 transition ease-in-out delay-50 hover:-translate-y-1 hover:scale-110"
            >
              <Image src={Hashtag} width={100} height={100} />
              <h3 className="texl-lg font-medium pt-2 pb-8">ReactJS API</h3>
              <p>A todo-list made with ReactJS</p>
            </a>
            <a
              href="https://github.com/Luchassmed"
              target="_blank"
              className="text-center shadow-lg p-10 rounded-xl my-10 transition ease-in-out delay-50 hover:-translate-y-1 hover:scale-110"
            >
              <Image src={Hashtag} width={100} height={100} />
              <h3 className="texl-lg font-medium pt-2 pb-8">
                Tilebased game in Java
              </h3>
              <p>CS-course project for exam</p>
            </a>
          </div>
        </section>
      </main>
    </div>
  );
}
